### PR TITLE
feat(#9): Fix flexi_logger error working with local time

### LINKED ISSUE #9: flexi_logger error working with local time
Error message:
`[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset`

Documented in:
[issue #99 of flexi_logger](https://github.com/emabee/flexi_logger/issues/99)
[rustsec](https://rustsec.org/advisories/RUSTSEC-2020-0159)

### PR DESCRIPTION
**Pull request by tomasalagoa**
fixes #9

### CODE REVIEW

File: src/bin/nabu/main.rs [hunk 1]
```diff
@@ -43,10 +43,13 @@ fn main() -> Result<()> {
...
     ctrlc::set_handler(move || {
         r.store(false, Ordering::SeqCst);
-    }).expect("Error setting Ctrl-C handler");
+    })
+    .expect("Error setting Ctrl-C handler");
 
     let level = if cli.debug { "debug" } else { "info" };
-    Logger::try_with_str(level)?.start()?;
+    let mut logger = Logger::try_with_str(level)?;
+    logger = logger.use_utc();
```
Comment (jmg-duarte) [inline src/bin/nabu/main.rs:51]: Is there a way we can configure this during construction?

Comment (tomasalagoa) [reply src/bin/nabu/main.rs]: Definitely, fixed in 07e0e0d26515feda14494512c11aa53b524a9902
